services:
  - type: web
    name: summaize-api
    runtime: docker
    plan: starter
    repo: https://github.com/yourusername/summaize.git  # Replace with your actual repository URL
    branch: main
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
    autoDeploy: true
